#!/usr/bin/env python3
"""Build a compact, local routing catalog for the generic MCP skill."""

import argparse
import json
from pathlib import Path


VALID_TYPES = {"library", "configuration", "standard", "application", "integration"}


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path, help="Local JSON manifest")
    parser.add_argument("--output", type=Path, required=True, help="Generated Markdown catalog")
    return parser.parse_args()


def validate_entry(entry, source_ids):
    required = ("id", "type", "source_modules", "capabilities")
    missing = [key for key in required if not entry.get(key)]
    if missing:
        raise ValueError("Catalog entry is missing: %s" % ", ".join(missing))
    if entry["type"] not in VALID_TYPES:
        raise ValueError("Unsupported type for %s: %s" % (entry["id"], entry["type"]))
    unknown = set(entry["source_modules"]) - source_ids
    if unknown:
        raise ValueError("Unknown source modules for %s: %s" % (entry["id"], ", ".join(sorted(unknown))))


def build_catalog(manifest):
    sources = manifest.get("sources", [])
    source_ids = {
        "%s:%s" % (source["id"], module["id"])
        for source in sources
        for module in source.get("modules", [])
    }
    entries = manifest.get("catalog", [])
    for entry in entries:
        validate_entry(entry, source_ids)

    lines = [
        "# Generated knowledge catalog",
        "",
        "Generated by `catalog_generator.py`; do not edit manually.",
        "This file is routing metadata only. The MCP remains the source of answers.",
        "",
    ]
    for entry in sorted(entries, key=lambda item: item["id"]):
        status = entry.get("status", "ready")
        lines.append("## %s [%s, %s]" % (entry["id"], entry["type"], status))
        if entry.get("aliases"):
            lines.append("- aliases: %s" % ", ".join(entry["aliases"]))
        lines.append("- sources: %s" % ", ".join(entry["source_modules"]))
        lines.append("- capabilities: %s" % ", ".join(entry["capabilities"]))
        lines.append("")
    return "\n".join(lines)


def main():
    args = parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    catalog = build_catalog(manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(catalog, encoding="utf-8")
    print("Generated %s" % args.output)


if __name__ == "__main__":
    main()
